### ISSUE TITLE
Linux Mint doesn't install nuvolaplayer3-all-services by default

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaplayer#107]
From [Try Nuvola Player 3 Beta (Cloud Music Player With Tight Desktop Integration)](http://www.webupd8.org/2015/06/try-nuvola-player-3-beta-cloud-music.html):

> While Linux Mint is not officially supported, you can simply select Ubuntu 14.04 LTS in the installer and it should work. Howerver, Linux Mint doesn't install packages listed under "Recommends" and because of this, Flash Player as well as the Nuvola Player 3 services won't be installed and you'll have to install them manually (install "nuvolaplayer3-all-services" to get all the Nuvola Player 3 services and one of the following packages for Flash Player: adobe-flashplugin, flashplugin-installer or freshplayerplugin).

It is necessary to move to hard dependencies.

**Comment by fenryxo** [comment]
This ticket has been added to the roadmap for July 2015 tiliado/nuvolaplayer.project#4

**Comment by hackel** [comment]
Meh, if Linux Mint doesn't install recommended packages by default, it's their problem, isn't it?  That's the whole point of the recommends field.  I always disable installing recommends on my Debian and Ubuntu boxes, since I want more control of the cruft.  I assume that's why Mint has done the same.  The fact is, Nuvola does *not* depend on these packages, but it can make use of them.

Oh well, though I don't agree, this is a very minor thing and I will survive! :)

**Comment by fenryxo** [comment]
> Meh, if Linux Mint doesn't install recommended packages by default, it's their problem, isn't it?

I don't care about Linux Mint, but I do care about users. If the users open Nuvola Player and see empty window (no services installed), they might get confused. That must not happen.
