### ISSUE TITLE
Feature request: Autostart a specific service (or ability to do it from cli)

### ISSUE THREAD

**Issue by TheAthenA714** [tiliado/nuvolaplayer#147]
Hi there!

Just discovered nuvolaplayer, really love it so far but I would like to make a small feature request. Nothing critical, just the ability to automatically launch a service when the app start. I basically use it exclusively with deezer, and I would like a way to open deezer directly without having to go through the service list page.

It doesn't have to be something integrated in the GUI or saved as a preference somewhere in a conf file, it could just be a launch option or a command in nuvolaplayer3ctl, but it would be nice to have.

Thank you again for your work!

**Comment by TheAthenA714** [comment]
Godfucking damn it I'm an idiot, I swear I tried every command line options I could find and I completely missed the fact that you can already do it. I'll be far away buried under a rock.

**Comment by Frozenfire92** [comment]
How did you do this?

**Comment by jrosco** [comment]
Depending on your OS / Windows Manager the services should all be individually located on the start menu under "Sound & Video"

**Comment by Frozenfire92** [comment]
@jrosco they are available and that is well documented how to access, however when doing keyboard shortcuts (or integrating with an application like [gnome-pie](https://github.com/Simmesimme/Gnome-Pie)) you need to be able to access the application executable or via the command line. 

## Example 1
I use Ubuntu Gnome and to add a keyboard shortcut (for my keyboard's media button) I need to type the command I would use to open on the command line. I looked through `nuvolaplayer3` and `nuvolaplayerctl` help options for how to do this but couldn't figure it out. The use case is opening a service directly (I only use google play music)

## Example 2
In Gnome Pie to add an application to the radial menu either you have to drag and drop the application from nautilus, or enter the command to open the application. I have found the services window in `/usr/share/applications` but none of the services links I can find individually through my applications menu

Please let me know if this makes sense, this is the one thing that is stopping my preferred workflow from working

**Comment by jrosco** [comment]
@Frozenfire92 try `cat ~/.local/share/applications/nuvolaplayer3-google-play-music.desktop | grep Exec`

That should be the command you're looking for ...

**Comment by Frozenfire92** [comment]
Thank you @jrosco !

This should be added to the documentation as I think it would be a common use case

The command for anyone who is like me and searching for this `nuvolaplayer3 -a google_play_music`

**Comment by jrosco** [comment]
no worries @Frozenfire92 feel free to add an issue regarding this, I see the `-a` option is not included in the `--help` menu

**Comment by fenryxo** [comment]
Hello. The missing `-a` argument in `--help` fixed in the git *master* & *3.0.x* branches of [Nuvola Player](https://github.com/tiliado/nuvolaplayer). Thanks for your feedback. The fix will be released in **Nuvola Player 3.0.1** (Nuvola Player 3.0 Stable Releases) and a next rebuild of **Nuvola Player 3.1.x** (Nuvola Player 3.1 Rolling Releases). To get informed when Nuvola Player 3.0.1 is released, follow Nuvola Player on [Facebook](https://www.facebook.com/nuvolaplayer), [Google+](https://plus.google.com/110794636546911932554) or [Twitter](https://twitter.com/NuvolaPlayer) or subscribe to the Nuvola Player Newsletter [weekly](http://eepurl.com/bLbm5H) or [monthly](http://eepurl.com/bLbtM1).

--

Jiří Janoušek, Nuvola Player Developer • *My work on Nuvola Player and user support are [funded by Nuvola Patrons](https://tiliado.eu/nuvolaplayer/funding/).*
