### ISSUE TITLE
Apps spread out outside of nuvolaplayer app

### ISSUE THREAD

**Issue by Spankalish** [tiliado/nuvolaplayer#162]
I don't know if this problem has been reported before, I had a quick look and haven't seen it. Anyway I recently installed nuvoplayer, which I think is a great idea. But on install all the cloud apps inside of nuvolaplayer were also outside of it mixed in with my actual apps. I don't think this is supposed to happen and if it is I don't like it. I would easily keep this app if the cloud apps stayed in the nuvolaplayer launcher. Its' a lot tidier. I had to uninstall because of this problem.

**Comment by fenryxo** [comment]
Hello @Spankalish. Thanks for your feedback. The desktop launchers for web apps was a frequently requested feature, so it's intentional. However, we can discuss how to make it less annoying for you. How about creating desktop launchers on demand only for web apps you actually use instead of creating desktop launchers for all web apps?

**Comment by fenryxo** [comment]
Changes landed in git master & 3.0.x branches. Will be available with the next rebuilt of packages.

* Nuvola Player doesn't create all app launchers on start-up, but only on demand.
* Added menu options Create app launchers and Delete app launchers.
* Launchers of currently running apps cannot be deleted.

![create_delete_app_launchers](https://cloud.githubusercontent.com/assets/853706/10381625/9b0c433a-6e1c-11e5-9f42-f5eb6dc32c9a.png)
