### ISSUE TITLE
Allow to install integration script independently on debian based distributions

### ISSUE THREAD

**Issue by skyghis** [tiliado/nuvolaplayer#164]
I would like to install only some integration script.

Today I can't install a single integration script because the package `nuvolaplayer3` has a dependency on package `nuvolaplayer3-all-services`.

The solution could be to remove the `nuvolaplayer3-all-services` or to set it as recommended.

**Comment by fenryxo** [comment]
Hello. Thanks for taking the time to report this issue.

In order to maintain consistency with Nuvola Player 2, installation of the `nuvolaplayer3` must lead to installation of all integration scripts. This is currently done by hard dependencies `nuvolaplayer3` → `nuvolaplayer3-all-services` → ... It is not possible to use "Recommends" relationship, because Linux Mint doesn't install recommended packages by default and users are confused as a result.

I plan alternate dependency chain for Nuvola Player 3.1 though (it's too late for such a change in 3.0 cycle):

* [ ] Rename `nuvolaplayer3` to `nuvolaplayer3-core` and remove dependency on `nuvolaplayer3-all-services`
* [ ] Update integration packages to depend on `nuvolaplayer3-core`.
* [ ] Rename `nuvolaplayer3-all-services` to `nuvolaplayer3`.

**Comment by fenryxo** [comment]
+1 from https://groups.google.com/d/msg/nuvola-player-devel/f3_xbboyJ4Q/Uh2SrEg3CAAJ

**Comment by fenryxo** [comment]
Alternate dependency chain has landed in the Nuvola Player 3.1 Rolling Releases repository. Thanks for your feedback.

* Each web app script depends on the `nuvolaplayer3-core` package only.
* The `nuvolaplayer3` metapackage, which depends on `nuvolaplayer3-all-services`, can be safely uninstalled.
