### ISSUE TITLE
Service Request: the new Grooveshark

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaplayer#175]
Reticketed from tiliado/nuvola-app-grooveshark#3. There is the "new Grooveshark" at http://grooveshark.im. It seems to be a [re-branded MP3Juice](https://torrentfreak.com/resurrected-grooveshark-is-actually-an-mp3juices-clone-150506/) actually.
##

**Comment by thepisu** [comment]
It seems to be just a frontend for Youtube music videos... like http://soundice.com.
It's interesting (because free and with a good design) but there are not legal terms / usage condition specified, and also using a video stream for listening only music waste bandwith usage.
I'm not sure this should be supported in Nuvola Player...

**Comment by fenryxo** [comment]
If any Nuvola Patron requests it, I will implement it. Otherwise, this task is in "postponed" queue and I have no personal interest in it.
