### ISSUE TITLE
Nuvola Player on Debian Stretch won't start up, log shows segfault

### ISSUE THREAD

**Issue by digitalgutenberg** [tiliado/nuvolaplayer#196]
Did a fresh install of the stable version of NP from the tiliado repo. It wouldn't start up, and nuvolaplayer3 --debug shows a segmentation fault. It did however start up when using sudo.

OS: Debian Stretch x86_64
DE: Gnome 3.18.2
Nuvola Player: 3.0.0 Revision 53b1d03843d1987c3510401da8959384fa25670e

debug: https://gist.github.com/digitalgutenberg/8d33c0b78d1dbb6a36bd

Let me know if more information is needed!

**Comment by fenryxo** [comment]
Hello @digitalgutenberg. Thanks for your report. It is now necessary to obtain a backtrace. Could you do it? I've updated [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#get-backtrace) with instructions.

**Comment by digitalgutenberg** [comment]
Here you go: https://gist.github.com/digitalgutenberg/c1f9f7b9c68d29484d18

Just a note about your addition to the Bug Reporting Guidelines; my system didn't have gdb preinstalled.

**Comment by fenryxo** [comment]
> Here you go: https://gist.github.com/digitalgutenberg/c1f9f7b9c68d29484d18

Unfortunately, the log doesn't include the backtrace. It seems you missed step 5: Type `bt<Enter>` to obtain the backtrace.

> Just a note about your addition to the Bug Reporting Guidelines; my system didn't have gdb preinstalled. Could you try again?

Thanks, I've updated the instructions.

**Comment by digitalgutenberg** [comment]
Oops, sorry about that, my bad!

Hopefully I didn't forget anything this time: https://gist.github.com/digitalgutenberg/99aab44e8c3ada9672c7

**Comment by fenryxo** [comment]
Thanks. It seems to be same issue I've been working on in #197. Will be hopefully fixed soon.

**Comment by fenryxo** [comment]
Fixed in the git *master* & *0.2.x* branches of [Diorite library](https://github.com/tiliado/diorite). Thanks for your bug report.

The fix will be released in **Diorite 0.2.1** (Nuvola Player 3.0 Stable Releases) and a next rebuild of **Diorite 0.3.x** (Nuvola Player 3.1 Rolling Releases). To get informed when Diorite 0.2.1 is released,

  * follow Nuvola Player on [Facebook](https://www.facebook.com/nuvolaplayer),
    [Google+](https://plus.google.com/110794636546911932554) or
    [Twitter](https://twitter.com/NuvolaPlayer).
  * subscribe to the Nuvola Player Newsletter: [weekly](http://eepurl.com/bLbm5H)
    or [monthly](http://eepurl.com/bLbtM1).
