### ISSUE TITLE
Incorrect work in Ubuntu 14.04

### ISSUE THREAD

**Issue by tashimotor** [tiliado/nuvolaplayer#218]
![2016-04-07 16 40 31](https://cloud.githubusercontent.com/assets/14804351/14353056/0f61ce92-fce0-11e5-9094-d627f72b533e.png)
No control buttons in bottom panel and in unity sound applet.
Incorrect display of whole page(different from google play music)

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
x86_64

version 3.0.1
revision 018a1322200541ee7c37
google play music script 5.12

[https://gist.github.com/tashimotor/f4ff387320581125c83f3f266fe00f13](url)

**Comment by fenryxo** [comment]
Hello @tashimotor. Thanks for taking time to report this issue. Does it also happen in [WebKitGtk MiniBrowser](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#webkitgtk-minibrowser)?

**Comment by tashimotor** [comment]
Yes, it is same issue.

07.04.2016 17:08, Jiří Janoušek пишет:
>
> Hello @tashimotor <https://github.com/tashimotor>. Thanks for taking 
> time to report this issue. Does it also happen in WebKitGtk 
> MiniBrowser 
> <https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#webkitgtk-minibrowser>?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/tiliado/nuvolaplayer/issues/218#issuecomment-206923413>
>

-- 
/Александр
+7 926 441-35-96 /

**Comment by fenryxo** [comment]
It seems like a WebKitGtk issue then. It will hopefully disappear when Nuvola Player packages are rebuilt to use the WebKitGTK+ 2.8.5 library provided by the WebKit team instead of the too old WebKitGTK+ library from the Ubuntu repository (see #216 for details).

**Comment by fenryxo** [comment]
The repository of **the Nuvola Player 3.1 Rolling Releases** now contains the WebKitGTK 2.8.5 packages for Ubuntu 14.04 and Nuvola Player packages for this distribution have been rebuilt to use them instead of the old WebKitGTK packages provided by Ubuntu. **This should fix all rendering/integration issues that had occurred only in Ubuntu 14.04.** Nuvola Patrons and other people with access to the rolling releases are welcome to try them out. If no problems are found, same trick will be made also for Nuvola Player 3.0 Stable Releases eventually.

**Comment by fenryxo** [comment]
The repository of **the Nuvola Player 3.0 Stable Releases** now contains the WebKitGTK 2.8.5 packages for Ubuntu 14.04 and Nuvola Player 3.0.2 packages for this distribution have been built to use them instead of the old WebKitGTK packages provided by Ubuntu. **This should fix all rendering/integration issues that had occurred only in Ubuntu 14.04.**
