### ISSUE TITLE
Google Play Music rendered incorrectly

### ISSUE THREAD

**Issue by pszi1ard** [tiliado/nuvolaplayer#219]
Recently Google Play Music has been rendering incorrectly which also affects the functionality because often some interface elements end up hidden behind others or non-functional.

```
$ cat /etc/lsb-release | tail -n1
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
```
```
$ uname -m
x86_64
```
```
$ nuvolaplayer3 --version
Nuvola Player 3 3.0.1
Revision 018a1322200541ee7c378b2418d497ddd17bae15
```

Below is example of the broken interface.

![screenshot from 2016-04-13 18 41 19](https://cloud.githubusercontent.com/assets/1333767/14501628/a1ef15b4-01a7-11e6-9cf8-88ce764edbd3.png)

**Comment by fenryxo** [comment]
Hello @pszi1ard. Thanks for taking the time to report this issue. It seems to be an incompatibility between Google Play Music website and a too old WebKitGTK library in Ubuntu 14.04. It will hopefully disappear when Nuvola Player packages are rebuilt to use the WebKitGTK+ 2.8.5 library provided by the WebKit team instead (see #216 for details).

**Comment by pszi1ard** [comment]
Great, thanks for the quick feedback!

**Comment by fenryxo** [comment]
The repository of **the Nuvola Player 3.1 Rolling Releases** now contains the WebKitGTK 2.8.5 packages for Ubuntu 14.04 and Nuvola Player packages for this distribution have been rebuilt to use them instead of the old WebKitGTK packages provided by Ubuntu. **This should fix all rendering/integration issues that had occurred only in Ubuntu 14.04.** Nuvola Patrons and other people with access to the rolling releases are welcome to try them out. If no problems are found, same trick will be made also for Nuvola Player 3.0 Stable Releases eventually.

**Comment by fenryxo** [comment]
The repository of **the Nuvola Player 3.0 Stable Releases** now contains the WebKitGTK 2.8.5 packages for Ubuntu 14.04 and Nuvola Player 3.0.2 packages for this distribution have been built to use them instead of the old WebKitGTK packages provided by Ubuntu. **This should fix all rendering/integration issues that had occurred only in Ubuntu 14.04.**
