### ISSUE TITLE
Let user to disable media keys grabbing

### ISSUE THREAD

**Issue by christophschw** [tiliado/nuvolaplayer#237]
**This issue has been fixed in the [master](https://github.com/tiliado/nuvolaplayer) & [3.0.x](https://github.com/tiliado/nuvolaplayer/tree/3.0.x) GIT branches. Thanks for making Nuvola Player better by creating bug reports.**

This issue has been fixed in the [Nuvola Player 3.0.4 Stable Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.0/install.html) (September 17th, 2016). It will be also available with the next rebuilt of packages of the [Nuvola Player 3.1 Rolling Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.1/install.html).

---

**Details:**

Nuvola Player always grabs media keys. User should be allowed to disable this feature and use media keys in other applications.

* Implementation detail: Create MediaKeysComponent and add its switch to the Preferences dialog to let user turn this feature off .
* Tentatively scheduled for July 2016.
* Related: tiliado/nuvolaplayer#230

---

**Original report: Media Keys in Plasma 5**

Hey,

thanks for this nice application! I really like to use it.

Unfortunately I got a problem: Nuvolaplayer 3.0.2 from the Fedora Repo 'steals' my global hotkeys in Plasma 5. I'd like to control the Player via MPRIS and Plasma's media control, but it seems that Nuvola blocks the global hotkeys. I can confirm this with 'xev': As long as Nuvola is running there's no Xf86Play-Event anymore.

At the moment I use the global hotkeys of the Spotify app. But everytime I use another player I have to kill Nuvola...

Would it help to block the Nuvola's key grabber? How could I do this?

Thank you!

**Comment by fenryxo** [comment]
Hello @christophschw. Thanks for taking the time to report this issue. Currently, it is not possible to disable media keys grabbing in Nuvola Player but it should definitely be fixed. Tentatively scheduled for July 2016.

**Comment by christophschw** [comment]
Thanks for the answer and nice to hear you'll fix it!

**Comment by fenryxo** [comment]
**This issue has been fixed in the [master](https://github.com/tiliado/nuvolaplayer) & [3.0.x](https://github.com/tiliado/nuvolaplayer/tree/3.0.x) GIT branches. Thanks for making Nuvola Player better by creating bug reports.**

This issue was fixed in the [Nuvola Player 3.0.4 Stable Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.0/install.html) (September 17th, 2016). It will be also available with the next rebuilt of packages of the [Nuvola Player 3.1 Rolling Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.1/install.html).
