### ISSUE TITLE
Global shortcuts doesn't work anymore

### ISSUE THREAD

**Issue by kgaut** [tiliado/nuvolaplayer#239]
Seems that since this morning update (3.0.3) with Google Play Music 5.14 under Ubuntu 16.04 my global shortcuts (via media keys) doesn't work anymore.

They are working fine with other player.

![2016-06-07-17 24 47-screenshot](https://cloud.githubusercontent.com/assets/736910/15863809/c610482a-2cd4-11e6-926f-ea4f463928dc.png)

**Comment by fenryxo** [comment]
Hello @kgaut. Thanks for taking the time to report this issue. There was a bug in the Google Play Music script that might be related to this issue. Could you try out Google Play Music script 5.15?

**Comment by kgaut** [comment]
Great ! it's working again now. Cheers.

**Comment by fenryxo** [comment]
**This issue has been fixed in the [Google Play Music script 5.15](https://github.com/tiliado/nuvola-app-google-play-music). Thanks for your bug report.**

The fix is available in the [Nuvola Player 3.1 Rolling Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.1/install.html) repository as well as in the [Nuvola Player 3.0 Stable Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.0/install.html) repository.

**Comment by scotte** [comment]
Thanks for fixing this! I noticed recently that I couldn't use most of the nuvolaplayer3ctl commands as they were shown as "disabled". I spent some time investing it, but couldn't figure out the ultimate cause. With this patch and the 5.15 update to Google Play Music my problem is also resolved and my scripts are working again (yeah). Thanks!
