### ISSUE TITLE
Unable to access Preferences menu on Kubuntu 16.04

### ISSUE THREAD

**Issue by joshuafcole** [tiliado/nuvolaplayer#282]
The gear button dropdown contains only two groups of options rather than three. The preferences menu item is one of the missing options. I checked within two separate integrations (Google Music and Deezer, the latter being the example on the website with the preferences menu open) and within the main services selection window. 

Distribution: Kubuntu 16.04
DM/WM: Stock KDE 5.5.5integrations
Nuvola Premium Supporter: Yes
Nuvola Versions:

```
Nuvola Premium 3.1.1+201612311655.0856fd7
Revision 0856fd760f7877d0cb5e5666cb8cb51cd5b20f21
Diorite 0.3.1+201612311341.394a7f6
WebKitGTK 2.12.5
libsoup 2.52.2
```
![screenshot_20170109_125631](https://cloud.githubusercontent.com/assets/313870/21783178/193ce5a4-d66b-11e6-9608-3a81c135c7aa.png)

**Comment by fenryxo** [comment]
Hello @joshuafcole. Thanks for taking the time to report this issue. The Format support menu entry is missing as well.

Note to self: [Call set_app_menu() before create_menu_button()](https://github.com/tiliado/nuvolaplayer/blob/master/src/nuvolakit-runner/AppRunnerController.vala#L300)

**Comment by fenryxo** [comment]
**This issue has been fixed in the [master branch](https://github.com/tiliado/nuvolaplayer) and will be available with the next rebuilding of  packages of the [Nuvola Player 3.1 Rolling Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.1/install.html). Thanks for making Nuvola Player better by filing bug reports.**
