### ISSUE TITLE
Google Play Music app fails to connect to server

### ISSUE THREAD

**Issue by benmacleod** [tiliado/nuvolaplayer#287]
Ubuntu 16.04 x86_64 Unity
Nuvola Premium 3.1.1+201701141634.57169db
Revision 57169db3de0f131025120d3057bb76caf41267c9
Diorite 0.3.1+201701070954.7e16304
WebKitGTK 2.14.2
libsoup 2.52.2
Installed from Ubuntu repo using Tiliado Repositories app

The app takes a long time to load the first screen, and then when I attempt to play music, each track immediately shows the message "Couldn't play X" and then I get a message "Can't reach Google Play" within 1 second. When using Google Play Music from within Firefox on the same box, there is no trouble connecting to Google Play.

Here is an error log: https://gist.github.com/benmacleod/70050eac52c670c87095af42978c5b39

**Comment by fenryxo** [comment]
Hello @benmacleod. Thanks for taking the time to report this issue.

> The app takes a long time to load the first screen,

This is #279, which causes me a lot of headache. I hope to investigate it further this weekend.

> each track immediately shows the message "Couldn't play X" and then I get a message "Can't reach Google Play" within 1 second.

This usually happens when the Flash plugin crashes. Unfortunately, the new Flash plugin 24 crashes a lot under the WebKitGTK. Do you remember whether the issue also occurred before you have upgraded the Flash plugin?

**Comment by benmacleod** [comment]
Hey, @fenryxo, I'm not sure. I didn't trigger a Flash upgrade myself, but one might have happened when I ran a software update. I know it happened after updating Nuvola to version 3.1.1.

**Comment by fenryxo** [comment]
Does the issue occur with the today's update of Diorite library & Nuvola Player?

**Comment by benmacleod** [comment]
No, it works great! Thanks a lot :)
