### ISSUE TITLE
Recommend gstreamer1-plugin-mpg123 for Fedora 25+

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaplayer#343]
Reticketed from #334 
> there is now gstreamer1-plugin-mpg123 officially available F25+, so you probably want to recommend this in documentation

Update: https://tiliado.github.io/nuvolaplayer/documentation/3.0/install-fedora.html

**Comment by voxik** [comment]
I was originally referring to:

https://github.com/tiliado/nuvolaplayer/wiki/Web-App-Requirements

Just FTR, this is due to expired mp3 patents:

https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/PUCTFFYU5L2A3L7QVME7TOMX3R6WIO2F/#34NPNTJITRHRP2FRKKYGL2YMEUU4BDYF

So things might also get better on other distributions, not sure, just saying ...

**Comment by fenryxo** [comment]
> I was originally referring to:
> https://github.com/tiliado/nuvolaplayer/wiki/Web-App-Requirements

This page is up-to-date. There is not a single word about Fedora or its packaging.
