### ISSUE TITLE
Is ARM architecture supported?

### ISSUE THREAD

**Issue by rinaldus** [tiliado/nuvolaplayer#496]
I want to install Nuvola Apps on my Raspberry Pi 3, because it better solution, than run music services in heavy browser. Is possible to run Nuvola Apps on ARM architecture? And if it's not possible, can you add ARM support in future?

**Comment by fenryxo** [comment]
Hello @rinaldus. I currently build Nuvola only for x86-64 so you cannot use the official Nuvola Flatpak packages on ARM. Since I have no experience with cross-compilation for ARM, I cannot even tell you whether it is possible to build Nuvola from source for ARM without any modifications and then run it on Raspberry Pi 3.

It's very unlikely that I'll add ARM support on my own. As I've written, I have no experience with cross-compilation for ARM, so I guess it would require more time than I can spare. On the other hand, I've been working on open-sourcing my flatpak recipes and refactoring & documenting Nuvola codebase to make it easier for new contributors to join the project. It would be awesome if somebody more appropriate for this task could step in and make the ARM port a reality.

**Comment by fenryxo** [comment]
You can start with cross-compilation of [Chromium Embedded Framework](https://github.com/tiliado/valacef/blob/master/BUILDING_CEF.md). I still build it outside flatpak-builder. It takes hours.

**Comment by fenryxo** [comment]
[Nuvola flatpak manifests are now public](https://github.com/tiliado/nuvola-flatpaks).

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
