### ISSUE TITLE
 Service Request: Owncloud [$25]

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaplayer#52]
From [Launchpad bug #1219083](https://bugs.launchpad.net/nuvola-player/+bug/1219083) by John Uren:

> An alternative to online music services are self-hosted music collections on a NAS or other storage device. [OwnCloud](https://owncloud.org/) uses [Ampache](http://ampache.org/) as its music server and Ampache can be installed as a separate service in itself. While Linux has a few programs that connect to the Ampache service, most are either additions to existing music collection apps or just plain ugly.

**Comment by fenryxo** [comment]
Hello everybody. I need more information in order to create Owncloud/Ampache script. Please ask following questions.

* Do you use standalone Ampache or integrated with Owncloud?
* Which version of Ampache and Owncloud do you use?
* Could you post a screenshot of your web player interface?
* Which URL (e.g. `http://localhost/ampache`) do you access the web player on?

**Comment by fenryxo** [comment]
Hi @AsavarTzeth. Your feedback is especially important since you have pledged a bounty for this feature.

**Comment by AsavarTzeth** [comment]
Well to start with, the ownCloud Music app as I understand it uses the Ampache API but is not itself an Ampache installation. So I would not go so far as to call it Ampache integrated with ownCloud. The reason this is titled Amapache/Owncloud is probably because the ownCloud Music App has implemented the Amapche API for streaming, among other things.

Anyhow, I use the ownCloud Music app, and I usually update it at the same time I update the ownCloud server, which is mostly quarterly.

I use the stable quarterly released version of ownCloud. I update it via their OBS supplied Debian/Ubuntu repository. In other words I follow the developers recommendations. Current version is 8.x.

I cannot supply my domain name because I don't want search engines or anyone else picking it up more than necessary.

My setup uses a fqdn, including a sub-domain that points to the ownCloud installation directly. The ownCloud Music App currently uses `https://fqdn/index.php/apps/music/#/` as its URL. The key here is that the fqdn must be a configurable variable for this to work. Additionally one have to keep in mind that some may opt to use a URL similar to this: `https://fqdn/owncloud`.

I will see if I can add a screenshot, but I currently don't use any image upload services and I am unsure how I can best share it.

**Comment by fenryxo** [comment]
Hello @AsavarTzeth. Thanks for your feedback.

> Well to start with, the ownCloud Music app as I understand it uses the Ampache API but is not itself an Ampache installation. So I would not go so far as to call it Ampache integrated with ownCloud. The reason this is titled Amapache/Owncloud is probably because the ownCloud Music App has implemented the Amapche API for streaming, among other things.

Ampache seems to have its own HTML5 web player, but it is not used by Owncloud. Let's dedicate this ticket to Owncloud Music then, I've created a new ticket for Ampache #212.

> Anyhow, I use the ownCloud Music app, and I usually update it at the same time I update the ownCloud server, which is mostly quarterly. I use the stable quarterly released version of ownCloud. I update it via their OBS supplied Debian/Ubuntu repository. In other words I follow the developers recommendations. Current version is 8.x.

Thanks for info. I've just installed [ownCloud 8.2.2](https://download.owncloud.org/download/repositories/stable/owncloud/) following your advice.

> I will see if I can add a screenshot, but I currently don't use any image upload services and I am unsure how I can best share it.

You can attach images to GitHub comments.

**Comment by fenryxo** [comment]
Hello @AsavarTzeth. [ownCloud Music script](https://github.com/tiliado/nuvola-app-owncloud-music) is finished. It requires the latest build of Nuvola Player 3.1 to function properly though.
