### ISSUE TITLE
Publish on Flathub

### ISSUE THREAD

**Issue by FastOSlinux** [tiliado/nuvolaplayer#606]
* [App Submission](https://github.com/flathub/flathub/wiki/App-Submission)
* [App Requirements](https://github.com/flathub/flathub/wiki/App-Requirements)

---

Original question:

Any reasons why these web apps are not on the flathub?

I would like to suggest at https://discourse.flathub.org/
the inclusion of NuvolaApps..

**Comment by fenryxo** [comment]
Hello @FastOSlinux. Thanks for your suggestion. The plan is to publish Nuvola 5 only on Flathub and discontinue my Flatpak repository.

The current show stopper for Flathub is that I build Chromium Embedded Framework separately outside Flatpak build environment whereas Flathub requires all components to be built inside the environment. That should change once Nuvola replaces CEF with QtWebEngine #587.

I would also like to switch back to an all-in-one application model instead of having Nuvola Service and individual Nuvola apps (Deezer, Spotify, etc.) because I don't want to maintain dozens Flatpak packages on Flathub.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
