### ISSUE TITLE
Also scrobble album to last.fm

### ISSUE THREAD

**Issue by dd23** [tiliado/nuvolaplayer#73]
Currently nuvola only scrobbles artist and track title to last.fm.

The last.fm API allows to (optionally) scrobble the **album name** for each track:
http://www.last.fm/api/show/track.scrobble

If we do have this information (on Google Music, we usually have it), then we can also send it to last.fm.

**Comment by fenryxo** [comment]
Hi. Thanks for taking the time to report this issue. I've added your feature request to [the wishlist](https://github.com/tiliado/nuvolaplayer/issues?q=is%3Aopen+label%3Awishlist+sort%3Acreated-asc).

**Comment by calhaus** [comment]
Same thing here! :)
I've noticed this on bandcamp and also on grooveshark at least. ;)

**Comment by fenryxo** [comment]
What's the benefit of scrobbling also the album name?

**Comment by dd23** [comment]
It does not change much, but you get some extra infos, such as:
 * http://www.last.fm/user/$(username)/tracks is grouped by albums
 * http://www.last.fm/user/$(username)/library/music/$(artist)/_/$(track) shows the album info, so you know which version of a song you were listening to (album, EP, single, etc.)
* http://www.last.fm/user/$(username)/albums is generated from that info, i think

**Comment by calhaus** [comment]
That^
Same song from an album, a demo or live ir different. Or a song with a same name but from different albuns also makes a difference and keeps your lastfm library organized which is important, if care about last.fm and you personal charts.

For me, for example, i care about my top of most listened albuns of the last 3 months, so i can remember what i have listened and if i want listen them again. If album name is not scrobbled i does not show up and i will probably forgot, because i discover lots of stuff in bandcamp.

Other example, listening several bands on bandcamp, that only have few or really recent things on spotify.
When i open the last.fm application on spotify, last.fm recommends Albuns based on the albuns i have listened, plus shows me if my most played albuns are on spotify and if i want to listen to them. ;)

So albuns info is kind of important in scroobling. Actually i stopped using nuvola and start using a chrome scroobler because of this.

P.S.: Also there are several apps that show albuns info and stuff like that, that people like to show up on personal pages/profiles, for example: http://lastfm.dontdrinkandroot.net/tools/user/albumcloud/page?3

**Comment by fenryxo** [comment]
Will fix this issue before Nuvola Player 3 stable, but not any time soon as there are other tickets with higher priority.

**Comment by fenryxo** [comment]
Fixed in git master & 3.0.x branches. Will be included in the next update of package repository.
