### ISSUE TITLE
Tidal playback is choppy and unlistenable

### ISSUE THREAD

**Issue by aybesea** [tiliado/nuvolaplayer#742]
This just started today. If I listen on Chrome, everything is fine. On Nuvola, it just keeps buffering and giving errors.

FWIW, Nuvola Amazon Music is perfect today. Just Tidal acting up, but as I stated not in my web broswer.

How do I fix this?

**Comment by nanga** [comment]
Hi @aybesea , I am having the same issue since yesterday (02-Jun-2021). I tried logging out from Tidal and logging back in, but things got worse, as it seems that I am blocked [1]. I suspect that something clearly got broken on Nuvola's end, since I am using the player from the same IP address that Nuvola player is reaching out the Internet and Tidal is playing just fine.
---
[1] 
![image](https://user-images.githubusercontent.com/25297244/120700919-a3f0dd80-c488-11eb-86dd-3cbe3048e213.png)

**Comment by fenryxo** [comment]
Hello @nanga, I've created a new ticket for your issue - #745.

**Comment by fenryxo** [comment]
Hello @aybesea. Thanks for reporting your issue. I need more information to investigate it further. Could you [visit the Bug reporting guidelined](https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines#basic-information) and answer the questions below?

* What is the version of Nuvola and Tidal on your system?
* What Linux distribution do you use and what is its version?
* Could you obtain a debugging log and attach it here as a file?
* Is the issue reproducible when you restart your system?

**Comment by fenryxo** [comment]
I got error `POST https://listen.tidal.com/v1/drm/licenses/widevine?token=CzET4vdadNUFQ5JU 400` in the JavaScript console.

**Comment by fenryxo** [comment]
> I got error `POST https://listen.tidal.com/v1/drm/licenses/widevine?token=CzET4vdadNUFQ5JU 400` in the JavaScript console.

`rm -rf ~/.var/app/eu.tiliado.NuvolaAppTidal/` helped though.

**Comment by fenryxo** [comment]
If anyone is affected by this issue, does running the command below when you quit Nuvola help?

```
mv ~/.var/app/eu.tiliado.NuvolaAppTidal ~/.var/app/eu.tiliado.NuvolaAppTidal-backup
```

**Comment by aybesea** [comment]
> If anyone is affected by this issue, does running the command below when you quit Nuvola help?
> 
> ```
> mv ~/.var/app/eu.tiliado.NuvolaAppTidal ~/.var/app/eu.tiliado.NuvolaAppTidal-backup
> ```

YES!!! After doing this it asked me to DL Widevine again, log in again, and I retried playback... and it works!!!

Why? What did this do for me?

**Comment by fenryxo** [comment]
The provided command renames Nuvola & Tidal data directory, so when Nuvola starts again, it won't find it and will create a fresh empty data directory. However, you will lose all your Nuvola settings. It is possible that you may need to repeat it in the future.

Since the fresh start works well, there is something fishy in the old Nuvola data files. If you have enough time, it is possible to investigate which particular file does cause the problem. Are you interested in this?
