### ISSUE TITLE
The TIDAL web player is not supported in this browser

### ISSUE THREAD

**Issue by taboadaa** [tiliado/nuvolaplayer#764]
**Unfortunately, Tidal is currently incompatible with Nuvola Player and there is no feasible workaround.** Per [our terms](https://nuvola.tiliado.eu/terms/), the service has been marked as deprecated and affected Nuvola Player users may ask for a refund of their Nuvola Player license.

Reason for the incompatibility: Tidal shows requires newer browser engine showing message  message "The TIDAL web player is not supported in this browser".

---

Original report:
I reinstalled Tidal because I had issue #742  and now after a fresh start there is this message:

```
The TIDAL web player is not supported in this browser
Switch browser or press button underneath to download the TIDAL desktop player.
[Download TIDAL]
```

Here are the version of my app:
Tidal script: 1.3.0 (0-g90f411a)
Nuvola Player: 4.23.0 (0g3ab9c9a)
Libs: Diorite: 4.23.0, Chromium 75.0.3770.100, ValaCEF 75.3770.16, libsoup 2.72.0

Thanks!

**Comment by fenryxo** [comment]
Hello @taboadaa, thanks for your bug report. I apologize for the late response.
 
Unfortunately, Tidal is no longer compatible with Nuvola's web engine. This may change once Nuvola is ported to the new web engine in #583. Since I haven't managed to find any workaround to make Tidal work until then, Tidal is no longer supported in Nuvola.

Per [our terms](https://nuvola.tiliado.eu/terms/), the service has been marked as deprecated and affected Nuvola Player users may ask for a refund of their Nuvola Player license.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
