### ISSUE TITLE
Hardcoded Icons for Scripts are not themable

### ISSUE THREAD

**Issue by Atema** [tiliado/nuvolaplayer#78]
Currently, the Web App Scripts have hardcoded icons, which are located in non-standard directories and therefore not themable.

The icons *should* be placed in either ```/usr/share/icons/hicolor/[size]/apps/[icon name]``` or ```~/.local/share/icons/hicolor/[size]/apps/[icon name]```.

**Comment by fenryxo** [comment]
Hi. Thanks for taking the time to report this issue. I've added your request to [the wishlist](https://github.com/tiliado/nuvolaplayer/issues?q=is%3Aopen+label%3Awishlist+sort%3Acreated-asc).

**Comment by fenryxo** [comment]
Fixed in git master & 3.0.x branches. Will be available with the next rebuilt of packages. Thanks for your bug report.

Nuvola Player now tries looking for theme icons called `nuvolaplayer3_APP_ID`,
e.g. `nuvolaplayer3_google_play_music`, then falls back to hard-coded icon paths in order to maintain backward compatibility. However, only Google Play Music script currently provides a whole iconset. Other scripts will follow though.
