### ISSUE TITLE
Youtube Music Script - unable login

### ISSUE THREAD

**Issue by master-sushi** [tiliado/nuvolaplayer#783]
## YouTube Music is no longer supported

Unfortunately, YouTube Music has become incompatible with the old web engine in Nuvola Player and no workaround has been found. Since  [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea), the effort to port Nuvola Player to a new web engine was canceled as well.

We apologize that we cannot fix the issue. Per [our terms](https://nuvola.tiliado.eu/terms/), affected users may ask for a partial refund of their Nuvola license purchase.

## Original report

Hi, 

login with Google Account wont work, because browser security issues.

![Snímek z 2022-01-20 17-52-55](https://user-images.githubusercontent.com/20931086/150385829-a91de77a-b637-486a-afa0-fa7f865a1299.png)

**Comment by jiri-janousek** [comment]
Hello @master-sushi, thanks for reporting the issue. Unfortunately, YouTube Music has become incompatible with the old web engine in Nuvola Player and I haven't managed to find any workaround for it. Since  [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea), the effort to port Nuvola Player to a new web engine was canceled as well.

I'm sorry that I cannot fix the issue. Per [our terms](https://nuvola.tiliado.eu/terms/), you may ask for a partial refund of your Nuvola license purchase.

**Comment by master-sushi** [comment]
@jiri-janousek thanks fot reply. Do you plan development of new Nuvola version on future? Thank you.

**Comment by jiri-janousek** [comment]
No new features are planned, only bug fixes when feasible.

**Comment by kd8bny** [comment]
I loved this thing

**Comment by razzeee** [comment]
We'll I guess I shouldn't have done a reinstall :(

**Comment by razzeee** [comment]
Hrm, if I have a data/config dir on another PC, could I copy that folder over to a new install?
Would you know, where to find these?

**Comment by jiri-janousek** [comment]
The data of Flatpak apps are in `~/.var/app/` (`~` is your home directory). The data of Nuvola Player YouTube Music app are in `~/.var/app/eu.tiliado.NuvolaAppYoutubeMusic`.

**Comment by razzeee** [comment]
Thank you, copying that data from one of my other systems seems to fix the problem for me.
