### ISSUE TITLE
Service Request: Youtube

### ISSUE THREAD

**Issue by AltarBeastiful** [tiliado/nuvolaplayer#83]
With Youtube adding a music tab, automatic playlists and such, it's very close to a regular music streaming service. Could be interesting to support it.

This request was previously rejected [a few years ago][1], but it might be time to reconsider it.

Could the video be a problem here?

[1]: https://blueprints.launchpad.net/nuvola-player/+spec/add-youtube-service

**Comment by fenryxo** [comment]
Hi. Thanks for your idea how to make Nuvola Player better. I've added your feature request to [the wishlist](https://github.com/tiliado/nuvolaplayer/issues?q=is%3Aopen+label%3Awishlist+sort%3Acreated-asc) with a default low priority. Since Nuvola Player project is [underfunded](https://tiliado.eu/nuvolaplayer/funding/), it can take a while before I process older feature requests and will start working on this issue. You can support your wish via [PayPal](https://tiliado.eu/nuvolaplayer/funding/#donate-wishlist) or [BountySource](https://www.bountysource.com/issues/9655329-service-request-youtube) to raise its priority though.

Jiří Janoušek, Nuvola Player Developer • *My work on Nuvola Player and user support are [funded by Nuvola Patrons](https://tiliado.eu/nuvolaplayer/funding/).*

**Comment by fenryxo** [comment]
Code review in progress: https://github.com/jrosco/nuvola-app-youtube/issues/1

**Comment by jrosco** [comment]
Did some refactoring to better handle TypeError that were occurring . Created a pull request here https://github.com/jrosco/nuvola-app-youtube/pull/2

**Comment by fenryxo** [comment]
Hello @jrosco, feel free to merge your pull request. When I'll get to the code review, I will take a look at the master branch only ignoring any not yet merged pull requests.

**Comment by fenryxo** [comment]
Youtube script has been released.
