### ISSUE TITLE
Nuvola Player doesn't respond to media keys in Mate desktop environment

### ISSUE THREAD

**Issue by rathboma** [tiliado/nuvolaplayer#86]
I'm using Mint 17.1 Mate edition and pressing Back/Play/Next keys does nothing. I'm using Nuvola Player 3 Beta.

This is due to a namespace change in Mate vs the original Gnome namespace used in Gnome2 (and 3).

There's a discussion on the topic here - http://forums.linuxmint.com/viewtopic.php?f=47&t=102626

Not sure how hard this would be to do, but it would be great for us Mate users.
##

**Comment by fenryxo** [comment]
Hi. Thanks for your idea how to make Nuvola Player better. I've added your feature request to [the wishlist](https://github.com/tiliado/nuvolaplayer/issues?q=is%3Aopen+label%3Awishlist+sort%3Acreated-asc) with a default low priority. Since the wishlist is pretty long  and Nuvola Player project is [underfunded](https://tiliado.eu/nuvolaplayer/funding/), it can take a while before I will start working on this issue. However, you can support your wish via [PayPal](https://tiliado.eu/nuvolaplayer/funding/#donate-wishlist) or [BountySource](https://www.bountysource.com/issues/10013628-nuvola-player-doesn-t-respond-to-media-keys-in-mate-desktop-environment) to raise its priority. 

Jiri Janousek, Nuvola Player Developer • My work on Nuvola Player and user support are [funded by Nuvola Patrons](https://tiliado.eu/nuvolaplayer/funding/).

**Comment by dkao** [comment]
MATE uses MPRIS2 to send media keys.
Support needs to be added in mate-settings-daemon. e.g.
```
diff --git a/plugins/mpris/msd-mpris-manager.c b/plugins/mpris/msd-mpris-manager.c
index 1427044..3adf56f 100644
--- a/plugins/mpris/msd-mpris-manager.c
+++ b/plugins/mpris/msd-mpris-manager.c
@@ -51,7 +51,7 @@
 
 /* Number of media players supported.
  * Correlates to the number of elements in BUS_NAMES */
-static const gint NUM_BUS_NAMES = 16;
+static const gint NUM_BUS_NAMES = 17;
 
 /* Names to we want to watch */
 static const gchar *BUS_NAMES[] = {"org.mpris.MediaPlayer2.audacious",
@@ -66,6 +66,7 @@ static const gchar *BUS_NAMES[] = {"org.mpris.MediaPlayer2.audacious",
                                    "org.mpris.MediaPlayer2.guayadeque",
                                    "org.mpris.MediaPlayer2.amarok",
                                    "org.mpris.MediaPlayer2.nuvolaplayer",
+                                   "org.mpris.MediaPlayer2.NuvolaPlayer3GooglePlayMusic",
                                    "org.mpris.MediaPlayer2.xbmc",
                                    "org.mpris.MediaPlayer2.xnoise",
                                    "org.mpris.MediaPlayer2.gmusicbrowser",
```

Although it's worth noting that nuvolaplayer2 was only called "org.mpris.MediaPlayer2.nuvolaplayer".
If nuvolaplayer3 uses a different name for each plugin it would get quite out of hand.

**Comment by fenryxo** [comment]
> If nuvolaplayer3 uses a different name for each plugin it would get quite out of hand.

Each Web App running in Nuvola Player 3 runtime is an independent process and has its own MPRIS interface. Mate Settings Daemon should get list of DBus names in run-time and handle all "org.mpris.MediaPlayer2.*" instances instead of maintaining a list of blessed media players.

**Comment by fenryxo** [comment]
FYI @dkao, the name of the MPRIS interface will likely change in the near future (#120):
 
`org.mpris.MediaPlayer2.NuvolaPlayer3GooglePlayMusic -> org.mpris.MediaPlayer2.GooglePlayMusicNuvolaApp`

**Comment by fenryxo** [comment]
> > If nuvolaplayer3 uses a different name for each plugin it would get quite out of hand.
> 
> Each Web App running in Nuvola Player 3 runtime is an independent process and has its own MPRIS interface. Mate Settings Daemon should get list of DBus names in run-time and handle all "org.mpris.MediaPlayer2.*" instances instead of maintaining a list of blessed media players.

Fixed upstream.

**Comment by fenryxo** [comment]
> Fixed upstream.

In mate-settings-damon 1.25.
