### ISSUE TITLE
Nuvolaplayer 3 doesn't show  the icons in the toolbar in KDE

### ISSUE THREAD

**Issue by Ralsa** [tiliado/nuvolaplayer#88]
The icons in the tool bar doesn't appears on KDE desktop. You can show it:  
http://i.imgur.com/cz17CZF.png?1

In Debian 8 I can fix it installing the Adwaita icon theme (gnome-default) but in Kubuntu 14.04 LTS it doesn't works. The icon theme doesn't exist in its repositories and the bug persist installing the theme form other sources.

**Comment by fenryxo** [comment]
Hi. Thanks for taking the time to report this issue. Since Nuvola Player 3 currently officially supports only GNOME and Unity, it is not tested in other desktop environments at all and it is expected that user experience and functionality might not be optimal.

I plan to add support for XFCE, Pantheon, Cinnamon and KDE (in that order) in the future  depending on project funding. If you don't like waiting, you can support this ticket via [PayPal](https://tiliado.eu/nuvolaplayer/funding/#donate-wishlist) or [BountySource](https://www.bountysource.com/issues/10233263-nuvolaplayer-3-doesn-t-show-the-icons-in-the-toolbar) to raise its priority. 

Jiri Janousek, Nuvola Player Developer • My work on Nuvola Player and user support are [funded by Nuvola Patrons](https://tiliado.eu/nuvolaplayer/funding/).

**Comment by Ralsa** [comment]
Ok, but I want to clarify that in Kubuntu 14.10 and Beta 15.04 (and Debian+KDE), with adwaita icon theme taken from Debian packages site, the the issue is fixed.
I supported Nuvolaplayer financially before and will go back and do it depending on the evolution of the project (and my possibilities).

**Comment by fenryxo** [comment]
> I supported Nuvolaplayer financially before and will go back and do it depending on the evolution of the project (and my possibilities).

Thanks for your support then. I've added tag Patron to raise the priority :-)

**Comment by fenryxo** [comment]
Kubuntu 14.04 works with [gnome-icon-theme-symbolic](http://packages.ubuntu.com/search?keywords=gnome-icon-theme-symbolic&searchon=names&suite=all&section=all). Will add this package to dependencies with the next rebuild. [Adwaita icon theme](http://packages.ubuntu.com/search?keywords=adwaita-icon-theme&searchon=names&suite=all&section=all) is available since Ubuntu Vivid.

**Comment by Ralsa** [comment]
Thank you very much. Issue fixed!

**Comment by fenryxo** [comment]
Packages uploaded, closing.

**Comment by fenryxo** [comment]
Work on this issue was funded by Nuvola Patrons: [2.55 hours, €25.50 EUR](https://tiliado.eu/nuvolaplayer/funding/task/39/).
