### ISSUE TITLE
Google Play Music crashes when trying to play music

### ISSUE THREAD

**Issue by thepaperpilot** [tiliado/nuvolaplayer#94]
This happened a couple days ago. I've heard Google changed something server-side, which breaks the unofficial gmusicapi that uses two factor authentication. Since I use 2fa, and it stopped working around the same time, I suspect it may be related.

I ran from the terminal, and found this error whenever it crashed:
[Runner:WARNING  Nuvola] AppRunnerController.vala:633: Communication failed: Failed to connect to socket '/tmp/libdiorite.nuvolaplayer3.google_play_music.webworker(thepaperpilot)'. Connection refused

To clarify, when I say crash I mean the top bar remains, but the web view goes away. Refresh and home buttons don't work.

**Comment by brnelsons** [comment]
Same happened to me. I just disabled the "Load Flash plugin" and all of the extensions. CTRL+Q to close. Reopened and re-enabled the flash plugin and the extensions: <edia Keys, Remote Player Interface, Notifications. everything works fine now

**Comment by fenryxo** [comment]
Hi @thepaperpilot. Thanks for taking time to report this issues. I will need more information to investigate it further.

> which breaks the unofficial gmusicapi

Nuvola Player doesn't actually use unofficial gmusicapi at all, so I think it is unrelated.

> [Runner:WARNING Nuvola] AppRunnerController.vala:633: Communication failed: Failed to connect to socket '/tmp/libdiorite.nuvolaplayer3.google_play_music.webworker(thepaperpilot)'. Connection refused

That means that the main Nuvola Player 3 process was not able to communicate with the web worker process (the web page). That probably happened because the web worker process had crashed and I need to get traceback of the crash from you. It involves installation of gdb and debugging libraries of GLib, GTK+ 3 and WebKitGTK (more than 1 GB of data). Are you willing to do that?

**Comment by fenryxo** [comment]
Hi @brnelsons. Thanks for you comment. How did you exactly "disabled the Load Flash plugin"?

**Comment by thepaperpilot** [comment]
I had uninstalled nuvola while waiting for a response, and having
reinstalled the program, the problem has gone away! I never touched the
config files, and haven't installed anything relevant, so I'm not sure how
to proceed from here. If it would still help, I wouldn't mind installing
the libraries.

**Comment by brnelsons** [comment]
@fenryxo I toggled the checkbox in the services i think and quit and reopened nuvola player

**Comment by fenryxo** [comment]
I'm closing this bug report as the issue seems to have disappeared. Feel free to reopen it when the issue appears again.
